PaceMaker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from PaceMaker.views import *

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('index/', HomeView.as_view(), name='index'),
                  path('',include('accounts.urls')),
                  path("classes/",include('classes.urls')),
                  path('grades/', include('grades.urls')),
                  path('community/', include('community.urls')),
                  path('graduate/', include('graduate.urls')),
                  path('course/', include('completion.urls')),
                  path('rank/', include('rank.urls')),
                  path('user/', UserView.as_view(), name='user'),
              ]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

community/urls.py
from django.urls import path, re_path

from community.views import *

app_name = 'community'

urlpatterns = [
    # # ex: /community/
    # path('', PostLV.as_view(), name='index'),

    # ex: /community/post_oldbook/
    path('post_oldbook/', OldbookLV.as_view(), name='post_ob'),

    # ex: /community/post_information/
    path('post_information/', InfoLV.as_view(), name='post_Info'),

    # ex: /community/post_Info/
    path('post_Info/', SearchFormView.as_view(), name='Info_list'),

    # ex: /community/post_ob/
    path('post_ob/', OBSearchFormView.as_view(), name='ob_list'),

    # ex: /Info/django-example/
    re_path(r'^Info/(?P<slug>[-\w]+)/$', PostDV.as_view(), name = 'Info_detail'),

    # ex: /Info/django-example/
    re_path(r'^ob/(?P<slug>[-\w]+)/$', OBPostDV.as_view(), name = 'ob_detail'),

    # post_Info/add/
    path('post_Info/add/', PostCreateView.as_view(), name="Info_add"),

    # post_ob/add/
    path('post_ob/add/', OBPostCreateView.as_view(), name="ob_add"),

    # /99/update/
    path('post_Info/<int:pk>/change/', PostUpdateView.as_view(), name="Info_update"),

    # /99/update/
    path('post_ob/<int:pk>/change/', OBPostUpdateView.as_view(), name="ob_update"),

    # /99/delete/
    path('post_Info/<int:pk>/delete/', PostDeleteView.as_view(), name="Info_delete"),

    # /99/delete/
    path('post_ob/<int:pk>/delete/', OBPostDeleteView.as_view(), name="ob_delete"),
]

rank/urls.py
from django.urls import path
from .views import *


app_name = "rank"
urlpatterns = [
    #path('', GradeLV.as_view(), name='index'),
    path('rank1/', Rank_One.as_view(), name='rank1'),
    path('rank2/', Rank_Two.as_view(), name='rank2'),
    path('rank3/', Rank_Three.as_view(), name='rank3'),
    path('rank4/', Rank_Four.as_view(), name='rank4'),
]

community/models.py
from django.db import models
from django.urls import reverse
from tagging.fields import TagField
from dataParser.models import StudentInfo
from django.utils.text import slugify

class PostIF(models.Model):
    title =  models.CharField('제목', max_length=50)
    slug = models.SlugField('슬러그', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('한줄 내용', max_length=100, blank=True,
                                   help_text='simple description text.')
    content = models.TextField('내용')
    tag = TagField('태그')
    create_date = models.DateTimeField('생성 날짜', auto_now_add=True)
    modify_date = models.DateTimeField('수정 날짜', auto_now=True)
    owner = models.ForeignKey(StudentInfo, on_delete=models.CASCADE)
    file = models.FileField('파일',blank=True, upload_to='documents/%Y/%m/%d')
    hits = models.IntegerField('조회수', default=0)
#tagField는 CharField를 상속받아서 디폴트로 amx_length=255,Blank=True로 정의하고 있어서 따로 내용을 안채워도됨


    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'post_if'
        ordering = ('-pk',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('community:Info_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(PostIF, self).save(*args, **kwargs)

class PostOB(models.Model):
    title =  models.CharField('제목', max_length=50)
    slug = models.SlugField('슬러그', unique=True, allow_unicode=True, help_text='one word for title alias.')
    description = models.CharField('한줄 내용', max_length=100, blank=True,
                                   help_text='simple description text.')
    content = models.TextField('내용')
    tag = TagField('태그')
    create_date = models.DateTimeField('생성 날짜', auto_now_add=True)
    modify_date = models.DateTimeField('수정 날짜', auto_now=True)
    owner = models.ForeignKey(StudentInfo, on_delete=models.CASCADE)
    file = models.FileField('파일',blank=True, upload_to='documents/%Y/%m/%d')
    hits = models.IntegerField('조회수', default=0)
    BUYSELL_CHOICES = (('사기','삽니다'),
                       ('팔기','팝니다'),)
    buysell = models.CharField('필수선택',max_length=10, choices=BUYSELL_CHOICES, default='Buy')
#tagField는 CharField를 상속받아서 디폴트로 amx_length=255,Blank=True로 정의하고 있어서 따로 내용을 안채워도됨


    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'
        db_table = 'post_ob'
        ordering = ('-pk',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('community:ob_detail', args=(self.slug,))

    def get_previous_post(self):
        return self.get_previous_by_modify_date()

    def get_next_post(self):
        return self.get_next_by_modify_date()

    def save(self, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.title, allow_unicode=True)
        super(PostOB, self).save(*args, **kwargs)
# Create your models here.

community/forms.py
from django import forms

# 커뮤니티 검색 forms
class PostSearchForm(forms.Form):
    search_word = forms.CharField(
        widget= forms.TextInput(
            attrs={'class':'form-control', 'placeholder': 'Search...'
                   }),
        label=False)

# 파일 업로드 forms
class DocumentForm(forms.Form):
    files =  forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

community/views.py
from django.views.generic import ListView, DetailView, TemplateView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from tagging.views import TaggedObjectList

from django.contrib.auth.mixins import LoginRequiredMixin
from community.models import PostIF,PostOB
from dataParser.models import StudentInfo

from django.views.generic.edit import FormView
from community.forms import PostSearchForm,DocumentForm
from django.db.models import Q
from django.shortcuts import render

# --- TemplateView
class TagTV(TemplateView):
    template_name = 'tagging/tagging_cloud.html'

# --- ListView
class OldbookLV(ListView):
    model = PostOB
    template_name = 'community/post_oldbook.html'
    context_object_name = 'posts'

    paginate_by = 5  # Display 5 objects per page

    def get_context_data(self, **kwargs):
        context = super(OldbookLV, self).get_context_data(**kwargs)
        paginator = context['paginator']
        context['totalCnt'] = PostOB.objects.all().count()
        page_numbers_range = 5  # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context

    def get_filter(self, **kwargs):
        sort = self.request.GET.get('sort','')

        if sort == 'mypost':
            sortfilter = PostOB.objects.filter(user=self.request.user).order_by('pk')
            return sortfilter
        elif sort == 'new':
            sortfilter = PostOB.objects.order_by('modify_date')
            return sortfilter

class InfoLV(ListView):
    model = PostIF
    template_name = 'community/post_Info.html'
    context_object_name = 'posts'

    paginate_by = 5 # Display 5 objects per page

    def get_context_data(self, **kwargs):
        context = super(InfoLV, self).get_context_data(**kwargs)
        paginator = context['paginator']
        context['totalCnt'] = PostIF.objects.all().count()
        page_numbers_range = 5 # Display only 5 page numbers
        max_index = len(paginator.page_range)

        page = self.request.GET.get('page')
        current_page = int(page) if page else 1

        start_index = int((current_page - 1) / page_numbers_range) * page_numbers_range
        end_index = start_index + page_numbers_range
        if end_index >= max_index:
            end_index = max_index

        page_range = paginator.page_range[start_index:end_index]
        context['page_range'] = page_range
        return context

class PostTOL(TaggedObjectList):
    model = PostIF
    template_name = 'tagging/tagging_post_list.html'

# --- DeatilView
class PostDV(LoginRequiredMixin,DetailView):
    model = PostIF
    template_name = 'community/Information_detail.html'

    def get_queryset(self):
        return PostIF.objects.all()    #filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(PostDV, self).get_context_data(**kwargs)
        obj = self.get_object()
        obj.hits = obj.hits + 1
        obj.save()
        return context


    # def count(self, **kwargs):
    #     context = super(PostDV, self).get_context_data(**kwargs)
    #     hit = context['hit']

    # def pageCounter(self,request):
    #     pk = request.GET['title']
    #     post = Post.objects.get(id=pk)
    #
    #     # 조회수를 늘린다.
    #     Post.objects.filter(id=pk).update(hits=Post.hits + 1)
    #
    #     return render('community/post_Info.html', {'post':post})

        # post = Post.objects.get(id=pk)
        # post.hits += 1
        # post.save()
        # return redirect('community/Information_detail.hmtl', {'post': post})

class OBPostDV(LoginRequiredMixin,DetailView):
    model = PostOB
    template_name = 'community/Oldbook_detail.html'

    def get_queryset(self):
        return PostOB.objects.all()    #filter(owner=self.request.user)

    def get_context_data(self, **kwargs):
        context = super(OBPostDV, self).get_context_data(**kwargs)
        obj = self.get_object()
        obj.hits = obj.hits + 1
        obj.save()
        return context

class SearchFormView(InfoLV,FormView):
    form_class = PostSearchForm
    template_name = 'community/post_Info.html'

    def form_valid(self, form):
        schWord = '%s' %self.request.POST['search_word']
        post_info_list = PostIF.objects.filter(Q(title__icontains=schWord)|Q(description__icontains=schWord)
                                        |Q(content__icontains=schWord)).distinct()

        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_info_list

        return render(self.request, self.template_name, context)

class OBSearchFormView(OldbookLV,FormView):
    form_class = PostSearchForm
    template_name = 'community/post_oldbook.html'

    def form_valid(self, form):
        schWord = '%s' %self.request.POST['search_word']
        post_oldbook_list = PostOB.objects.filter(Q(title__icontains=schWord)|Q(description__icontains=schWord)
                                        |Q(content__icontains=schWord)).distinct()
        context = {}
        context['form'] = form
        context['search_term'] = schWord
        context['object_list'] = post_oldbook_list

        return render(self.request, self.template_name, context)

# --- CRUD View
class PostCreateView(LoginRequiredMixin, CreateView):
    model = PostIF

    fields = ['title',  'description', 'content', 'file']
    initial = {'slug': 'auto-filling-do-not-input'}
    # slug 필드를 처리하는 또 다른 방법은 fields속성에서 제외해 폼에 나타나지 않도록 하는 방법입니다. \
    # 폼에는 보이지 않지만, Post 모델의 save()함수에 의해 테리블의 레코드에는 자동으로 채워집니다.
    # fields = ['title', 'description', 'content', 'tag']
    success_url = reverse_lazy('community:Info_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(PostCreateView, self).form_valid(form)

class OBPostCreateView(LoginRequiredMixin, CreateView):
    model = PostOB

    fields = ['buysell', 'title',  'description', 'content', 'file']
    initial = {'slug': 'auto-filling-do-not-input'}
    # slug 필드를 처리하는 또 다른 방법은 fields속성에서 제외해 폼에 나타나지 않도록 하는 방법입니다. \
    # 폼에는 보이지 않지만, Post 모델의 save()함수에 의해 테리블의 레코드에는 자동으로 채워집니다.
    # fields = ['title', 'description', 'content', 'tag']
    success_url = reverse_lazy('community:ob_list')

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super(OBPostCreateView, self).form_valid(form)


class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = PostIF
    fields = ['title', 'description', 'content', 'file']
    success_url = reverse_lazy('community:Info_list')

    def get_queryset(self):
        return PostIF.objects.filter(owner=self.request.user)

class OBPostUpdateView(LoginRequiredMixin, UpdateView):
    model = PostOB
    fields = ['title', 'description', 'content','file']
    success_url = reverse_lazy('community:ob_list')

    def get_queryset(self):
        return PostOB.objects.filter(owner=self.request.user)



class PostDeleteView(LoginRequiredMixin, DeleteView):
    model = PostIF
    success_url = reverse_lazy('community:Info_list')

    def get_queryset(self):
        return PostIF.objects.filter(owner=self.request.user)

class OBPostDeleteView(LoginRequiredMixin, DeleteView):
    model = PostOB
    success_url = reverse_lazy('community:ob_list')

    def get_queryset(self):
        return PostOB.objects.filter(owner=self.request.user)

# Create your views here.

community/templates/community/Information_detail.html
{% extends "base.html" %}
<!-- 별도로 html태그가 없으면 장고는 body영역으로 간주함-->
{% load static %}
{% block title %}Information_detail.html{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <div class="row">
            {#            <div class="col-lg-12">#}
            {#                <i><h1 class="page-header">정보 교류 </h1></i>#}
            {#            </div>#}

            <div class="panel heading">
                <h1 class="post-title">{{ object.title }}</h1>

                <div align="right">
                    <span class="post-date">{{ object.modify_date|date:"Y.m.d a H:i l" }}</span>
                    <a href="{{ site.url }}{{ page.url }}#disqus_thread" data-disqus-identifier="{{ page.id }}">댓글 보기</a>
                    <span  class="read">  조회수 {{ object.hits }}</span>
                </div>
            </div>

            <div class="panel body">
                <p align="right">
                    {% if postif.file %}
                        <a id="id_uploaded_file" href="" download>{{ PostIF.file.name }}</a>
                        파일 첨부:<a href="{{ postif.file.url }}" download>{{ postif.file.name }}</a>
                    {% endif %}
                </p>
                <br/><br/><br/>
                <p>{{ object.content|linebreaksbr }}</p>
                <br/><br/><br/>

                {% if postif.file %}
                    <img src="{{ postif.file.url }}" alt="">
                    <br/>
                {% endif %}

                <br/><br/><br/>

                <div>
                    {% if object.owner.hukbun == user.hukbun %}
                    <a class="btn btn-default pull-right" href="{% url 'community:Info_delete' object.id %}">Delete</a>
                    <a class="btn btn-default pull-right" href="{% url 'community:Info_update' object.id %}">Update</a>
                    {% endif %}
                    <a class="btn btn-default pull-left" href="{% url 'community:Info_list' %}" >목록</a>
                </div>

                <br/>
                <br/>
                <p class="other_posts">
                <h5 >{% if object.get_previous_by_modify_date %}
                    <a class="pull-left" href="{{ object.get_previous_post.get_absolute_url }}"
                       title="이전 게시물"> &laquo; Previous </a>
                {% endif %}
                    {#                    {{ object.get_previous_post }} {{ object.get_next_post }}#}
                    {% if object.get_next_by_modify_date %}
                        <a class="pull-right" href="{{ object.get_next_post.get_absolute_url }}" title="다음 게시물">  Next &raquo;</a>
                    {% endif %}</h5>
                </p>
            </div>

            <div class="panel modal-footer">
                <br/>
                <div>
                    {% load disqus_tags %}
                    {% disqus_show_comments %}
                </div>
            </div>
        </div>

    </div>
    {#    path: {{ post.file.path }}#}
    {#    url:  {{ post.file.url }}#}

    <script id="dsq-count-scr" src="//paker.disqus.com/count.js" async></script>
    <br/>

{% endblock %}

community/templates/community/Oldbook_detail.html
{% extends "base.html" %}
<!-- 별도로 html태그가 없으면 장고는 body영역으로 간주함-->

{% load static %}
{% block title %}Information_detail.html{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <h1 class="post-title">{{ object.title }}</h1>

            <div class="panel heading">
                <div align="right">
                    <span class="post-date">{{ object.modify_date|date:"Y.m.d a H:i l" }}</span>
                    <a href="{{ site.url }}{{ page.url }}#disqus_thread" data-disqus-identifier="{{ page.id }}">댓글 보기</a>
                    <span  class="read">  조회수 {{ object.hits }}</span>
                </div>
            </div>

            <div class="panel body">
                <p align="right">
                    {% if postob.file %}
                        <a id="id_uploaded_file" href="" download>{{ PostOB.file.name }}</a>
                        파일 첨부:<a href="{{ postob.file.url }}" download>{{ postob.file.name }}</a>
                    {% endif %}
                </p>
                <br/><br/><br/>
                <p>{{ object.content|linebreaksbr }}</p>
                <br/><br/><br/>

                {% if postob.file %}
                    <img src="{{ postob.file.url }}" alt="">
                    <br/>
                {% endif %}

                <br/><br/><br/>

                <div>
                    {% if object.owner.hukbun == user.hukbun %}
                        <a class="btn btn-default pull-right" href="{% url 'community:ob_delete' object.id %}">Delete</a>
                        <a class="btn btn-default pull-right" href="{% url 'community:ob_update' object.id %}">Update</a>
                    {% endif %}
                    <a class="btn btn-default pull-left"  href="{% url 'community:ob_list' %}" >목록</a>
                </div>

                {#                OnClick="location.href='{% url 'blog:update' %}'"#}
                <br/>
                <br/>
                <p class="other_posts">
                <h5 >{% if object.get_previous_by_modify_date %}
                    <a class="pull-left" href="{{ object.get_previous_post.get_absolute_url }}"
                       title="이전 게시물"> &laquo; Previous </a>
                {% endif %}
                    {#                    {{ object.get_previous_post }} {{ object.get_next_post }}#}
                    {% if object.get_next_by_modify_date %}
                        <a class="pull-right" href="{{ object.get_next_post.get_absolute_url }}" title="다음 게시물">  Next &raquo;</a>
                    {% endif %}</h5>
                </p>
            </div>

            <div class="panel modal-footer">
                <br/>
                <div>
                    {% load disqus_tags %}
                    {% disqus_show_comments %}
                </div>
            </div>
        </div>
    </div>

    <script id="dsq-count-scr" src="//paker.disqus.com/count.js" async></script>
    <br/>

{% endblock %}

community/templates/community/post_Info.html
{% extends "base.html" %}
{% load static %} {# css파일을 쓰려면 무조건 써줘야함 ! setting.py에서도 경로 설정 해줘야함 #}
{% block title %}정보교류 리스트{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <i><h1 class="page-header">정보 교류 게시판 </h1></i>
{#                <h4 align="right">총 게시물 수: {{ totalCnt }}</h4>#}
            </div>
            <!-- /.col-lg-12 -->

        <h5 align="right"><td>현재 게시물수 :{{ object_list.count }}</td></h5>
        <div class="dropdown pull-right">
            <button class="btn btn-default dropdown-toggle" type="button" data-toggle="dropdown">정렬
                <span class="caret"></span></button>
            <ul class="dropdown-menu">
                <li><a tabindex="-1" href="#">최신순</a></li>
                <li><a tabindex="-1" href="#">이름</a></li>
            </ul>
        </div>
        </div>

        <div>
            {% if object_list %}
                <table class="table table-striped table-hover">
                    <thead>
                    <tr>
                        <th >번호 </th>
                        <th>작성자</th>
                        <th>제목</th>
                        <th>등록일(수정일)</th>
                        <th>조회수</th>
                    </tr>
                    </thead>

                    <tbody>
                    {% for item in object_list %}
                        <tr >
                            <td>{{ item.pk }}</td>
                            <td>{{ item.owner.username }}</td>
                            <td>
                                <a href="{{ item.get_absolute_url }}" title="{{ item.description }}">{{ item.title }}</a>
                            </td>
                            <td>{{ item.modify_date|date:"Y / m / d" }}</td>
                            <td>{{ item.hits }}</td>
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <br/><br/><br/><br/>
                <i><h1 align="center"><span>게시글이 없네용~</span></h1></i>
                <br/><br/><br/><br/>
            {% endif %}
        </div>

        <a class="btn btn-default pull-right" OnClick="location.href='{% url 'community:Info_add' %}'">글쓰기</a>
        <br/><br/>

        <div align="center">
            <form class="form-inline" action="" method="post">{% csrf_token %}
                <div class="form-group ">
                    {{ form.as_table }}
                    <button class="btn btn-default " type="submit" value = "submit" ><span class="glyphicon glyphicon-search"></span></button>
                </div>

            </form>

        </div>
        {#--페이징--#}
        <div align="center">
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-end">
                    {% if page_obj.has_previous %}
                        <li class="page-link"><a href="?page={{ page_obj.previous_page_number }}"><span>이전</span></a></li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#"><span>이전</span></a>
                        </li>
                    {% endif %}

                    {% for page in page_range %}  {#페이징 숫자 범위를 5개로 하기위해서 view에서 만들어서 넘겨준것, paginator.page_range는 장고에서 기본 제공#}
                        <li class="page-item" {% if page == page_obj.number %}></li>
                            <li class="page-item active"{% endif %}>
                            <a href="?page={{ page }}">{{ page }}</a></li>
                    {% endfor %}

                    {% if page_obj.has_next %}
                        <li class="page-link"><a href="?page={{ page_obj.next_page_number }}"><span>다음</span></a></li>
                    {% else %}
                        <li class="page-item disabled">
                            <a href="#"><span>다음</span></a>
                        </li>
                    {% endif %}
                </ul>
            </nav>
        </div>
        <br/>

    </div>


{% endblock %}



{# <li {% if not page_obj.has_next %}class="disabled"{% endif %}>  #}

community/templates/community/post_confirm_delete.html
{% extends "base.html" %}
{% block title %}
    post_confirm_delete.html
{% endblock %}

{% block content %}

    <div align="center" id="content">
        <h1>Post Delete</h1>

        <form action="" method="post">{% csrf_token %}
            <p>Are you sure you want to delete "{{ object }} ?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>

{% endblock %}

community/templates/community/post_form.html
{% extends "base.html" %}
{% load static %} {# css파일을 쓰려면 무조건 써줘야함 ! setting.py에서도 경로 설정 해줘야함 #}
{% load widget_tweaks %}

{% block title %}커뮤니티 리스트{% endblock %}

{% block content %}
    <div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Write</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <h3 align="center">Blog Create/Update - {{ user.name }}</h3>

    <form action="." method="post">{% csrf_token %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        {% endfor %}


        <div class="center-block" style='width:300px'>
            <input class = "btn btn-default" type="submit" value="저장하기">
            <input class = "btn btn-default" type="reset" value="다시쓰기">
            <input class = "btn btn-default" type="button" value="Back" onclick="history.back(1)"></div>

        <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>
{% endblock %}
{#        {% if form.errors %}#}
{#            <p class="errornote">Wrong! Please correct the error(s) below.</p>#}
{#        {% endif %}#}

{#            <div class="form-group">#}
{#            <label for="subject">{{ form.title.label_tag }}</label>#}
{#            <input type="text" class="form-control" name ="subject" id="subject" placeholder="Enter title" >#}
{#                {{ form.title }}#}
{#            </div>#}
{##}
{#            <div class="form-group">#}
{#            <label for="slug">{{ form.slug.label_tag }}</label>#}
{#            <input type="text" class="form-control" name ="slug" id="slug" placeholder="slug">#}
{#                {{ form.slug }}#}
{#            </div>#}
{##}
{#            <div class="form-group">#}
{#            <label for="description">{{ form.description.label_tag }}</label>#}
{#            <input type="text" class="form-control" name ="description" id="description" placeholder="한줄로 쓰시오">#}
{#                {{ form.description }}#}
{#            </div>#}
{##}
{#            <div class="form-group">#}
{#            <label for="tag">{{ form.tag.label_tag }}</label>#}
{#            <input type="text" class="form-control" name ="tag" id="tag" placeholder="한줄로 쓰시오">#}
{#                {{ form.tag }}#}
{#            </div>#}
{##}
{#            <div class="form-group">#}
{#            <label for="content">{{ form.content.label_tag }}</label>#}
{#            <textarea class="form-control" rows="10" name="content" id="content"></textarea>#}
{#                {{ form.content }}#}
{#            </div>#}



{# <li {% if not page_obj.has_next %}class="disabled"{% endif %}>  #}

community/templates/community/postif_confirm_delete.html
{% extends "base.html" %}
{% block title %}
    postif_confirm_delete.html
{% endblock %}

{% block content %}

    <div align="center" id="content">
        <h1>게시글 삭제</h1>

        <form action="" method="post">{% csrf_token %}
            <p>"{{ object }}" 게시물을 삭제하시겠습니까?</p>
            <input type="submit" value="Confirm" />
        </form>
    </div>

{% endblock %}

community/templates/community/postif_form.html
{% extends "base.html" %}
{% load static %} {# css파일을 쓰려면 무조건 써줘야함 ! setting.py에서도 경로 설정 해줘야함 #}
{% load widget_tweaks %}

{% block title %}정보 공유 글쓰기{% endblock %}

{% block content %}
    <div id="page-wrapper">
    <div class="row">
        <div class="col-lg-12">
            <i><h3 class="page-header">정보 교류 글쓰기/업데이트- {{ user.username }}</h3></i>
        </div>
        <!-- /.col-lg-12 -->
    </div>

    <form action="." method="post" enctype="multipart/form-data">{% csrf_token %}

        {% for hidden in form.hidden_fields %}
            {{ hidden }}
        {% endfor %}

        {% for field in form.visible_fields %}
            <div class="form-group">
                <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                {{ field|add_class:'form-control' }}
                {% for error in field.errors %}
                    <span class="help-block">{{ error }}</span>
                {% endfor %}
            </div>
        {% endfor %}


        <div class="center-block" style='width:300px'>
            <input class = "btn btn-default" type="submit" value="저장하기">
            <input class = "btn btn-default" type="reset" value="다시쓰기">
            <input class = "btn btn-default" type="button" value="Back" onclick="history.back(1)"></div>

        <script type="text/javascript">document.getElementById('id_title').focus();</script>
    </form>
    </div>

{% endblock %}