PaceMaker/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from PaceMaker.views import *

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('index/', HomeView.as_view(), name='index'),
                  path('',include('accounts.urls')),
                  path("classes/",include('classes.urls')),
                  path('grades/', include('grades.urls')),
                  path('community/', include('community.urls')),
                  path('graduate/', include('graduate.urls')),
                  path('course/', include('completion.urls')),
                  path('rank/', include('rank.urls')),
                  path('user/', UserView.as_view(), name='user'),
              ]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

classes/urls.py
from django.urls import path, re_path
from .views import *

app_name='classes'
urlpatterns = [
    path('list/', majorLV.as_view(), name= 'major_list'),
    re_path(r'^(?P<pk>\d+)/$', majorDV.as_view(), name='major_detail'),

    path('retake/', RetakeRecommandView.as_view(), name= 'retake'),
    path('special/', SpecialCourseRecommandView.as_view(), name= 'special'),
    path('top/', TopStudentRecommandView.as_view(), name= 'top'),
    path('pre/', preCourseRecommandView.as_view(), name= 'pre'),
]

rank/urls.py
from django.urls import path
from .views import *


app_name = "rank"
urlpatterns = [
    #path('', GradeLV.as_view(), name='index'),
    path('rank1/', Rank_One.as_view(), name='rank1'),
    path('rank2/', Rank_Two.as_view(), name='rank2'),
    path('rank3/', Rank_Three.as_view(), name='rank3'),
    path('rank4/', Rank_Four.as_view(), name='rank4'),
]

classes/models.py
from django.db import models
from dataParser.models import Course

class classCourse(models.Model):
    # 년도
    year = models.CharField(max_length=15)
    # 학기
    semester = models.CharField(max_length=15)
    # 과목번호
    subjectCode = models.CharField(max_length=15)
    # 과목이름
    subjectName = models.CharField(max_length=50, blank=True, null=True)
    # 추천학년(학교에서)
    grade = models.CharField(max_length=50, blank=True, null=True)
    # 이수구분
    eisu = models.CharField(max_length=50, blank=True, null=True)
    # 학점
    score = models.CharField(max_length=50, blank=True, null=True)
    # 담당교수
    professor = models.CharField(max_length=50, blank=True, null=True)
    # 비고
    remarks = models.CharField(max_length=50, blank=True, null=True)
    # 교시
    time = models.CharField(max_length=50, blank=True, null=True)
    # 강의실
    lectureRoom = models.CharField(max_length=100, blank=True, null=True)
    # 학수코드
    huksu_code = models.CharField(max_length=50, blank=True, null=True)
    # 강의시수
    course_time = models.CharField(max_length=15, blank=True, null=True)
    # 설계시수
    design_score = models.CharField(max_length=15, blank=True, null=True, default="0")

    # table[1] 교과목 해설
    description = models.CharField(max_length=1000, blank=True, null=True)

    # table[2] 새부핵심역량 과의 관계
    # [지식응용, 검증능력, 문제해결, 도구활용, 설계능력, 팀웍스킬, 의사전달, 영향이해, 책임의식, 자기주도]
    Knowledge_application = models.CharField(max_length=5, blank=True, null=True)
    verification_ability = models.CharField(max_length=5, blank=True, null=True)
    problem_solving = models.CharField(max_length=5, blank=True, null=True)
    tool_utilization = models.CharField(max_length=5, blank=True, null=True)
    design_ability = models.CharField(max_length=5, blank=True, null=True)
    teamwork_skill = models.CharField(max_length=5, blank=True, null=True)
    communication = models.CharField(max_length=5, blank=True, null=True)
    understanding_of_influence = models.CharField(max_length=5, blank=True, null=True)
    responsibility = models.CharField(max_length=5, blank=True, null=True)
    self_led = models.CharField(max_length=5, blank=True, null=True)

    # # table[3] 교과목 학습목표
    # # [핵심역량, 세부핵심역량, 반영률, 학습목표, 수행준거, 성취목표, 평가방법]
    # core_competencies = models.CharField(max_length=10,blank=True, null=True)
    # detailed_core_competencies = models.CharField(max_length=10,blank=True, null=True)
    # reflectance = models.CharField(max_length=5,blank=True, null=True)
    # learning_objectives = models.CharField(max_length=200,blank=True, null=True)
    # performance_criteria = models.CharField(max_length=200,blank=True, null=True)
    # achievement_goals = models.CharField(max_length=5,blank=True, null=True)
    # evaluation_methods = models.CharField(max_length=10,blank=True, null=True)

    # table[4] 강의방법
    # [강의형태, 수업방식, 교육용기자재]
    Lecture_type = models.CharField(max_length=100, blank=True, null=True)
    teaching_method = models.CharField(max_length=100, blank=True, null=True)
    educational_equipment = models.CharField(max_length=100, blank=True, null=True)

    # table[5] 과제물
    # [과제물]
    Assignment = models.CharField(max_length=500, blank=True, null=True)

    # table[6] 성적 구성비율 존나 머리 안돌아가서 하드코딩되있음.
    # ['중간시험', '기말시험', '출석', '과제물및기타', '성적평가구분']
    Midterm_exam = models.CharField(max_length=10, blank=True, null=True)
    final_exam = models.CharField(max_length=10, blank=True, null=True)
    attendance = models.CharField(max_length=10, blank=True, null=True)
    assignments_and_others = models.CharField(max_length=10, blank=True, null=True)
    grading_division = models.CharField(max_length=10, blank=True, null=True)

    # table[7] 주별 강좌내용

    # table[8] 책
    # [도서명, 저자, 출판사, 출판년도]
    title = models.CharField(max_length=200, blank=True, null=True)
    author = models.CharField(max_length=300, blank=True, null=True)
    publisher = models.CharField(max_length=100, blank=True, null=True)
    year_of_publication = models.CharField(max_length=20, blank=True, null=True)

    # class Meta:
    #     unique_together = ('year', 'semester', 'subjectCode')

    def __str__(self):
        return self.subjectName + "\\" + self.year + "\\" + self.semester

class necessaryCourse(models.Model):
    year = models.CharField(max_length=6)
    childCourse = models.ForeignKey(classCourse, on_delete=models.CASCADE, related_name='necessary_child')
    parentCourse = models.ForeignKey(classCourse, on_delete=models.CASCADE, related_name='necessary_parent')


class promotedCourse(models.Model):
    year = models.CharField(max_length=6)
    childCourse = models.ForeignKey(classCourse, on_delete=models.CASCADE, related_name='promoted_child')
    parentCourse = models.ForeignKey(classCourse, on_delete=models.CASCADE, related_name='promoted_parent')

classes/views.py
from django.shortcuts import render
from dataParser.models import StudentInfo, Course, StudentGrade, Weekly_course_contents
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View, ListView, TemplateView
from datetime import datetime
from django.db.models import Q
from grades.views import getIntScore
import operator
from .models import classCourse, necessaryCourse, promotedCourse
from django.db.models import Count

def get_score_sum(hukbun):
    s = hukbun
    sum = 0
    scorelist = StudentGrade.objects.filter(hukbun=s).filter(valid='유효')
    scorelist = scorelist.exclude(grade__contains='P').values_list('score', flat=True)
    for i in scorelist:
        sum = sum + int(i)

    return sum

def get_avgGrade(hukbun):
    s = hukbun
    avg = 0.0
    sum = 0.0
    gradelist = StudentGrade.objects.filter(hukbun=s).filter(valid='유효').filter(
        Q(grade='A+') | Q(grade='A') | Q(grade='B+') | Q(grade='B') | Q(grade='C+') | Q(grade='C') | Q(grade='D+') | Q(
            grade='D'))
    for i in range(0, gradelist.count()):
        temp = getIntScore(gradelist[i].grade) * int(gradelist[i].score)
        sum = sum + temp
    score_sum = get_score_sum(hukbun)
    avg = sum / score_sum
    avg = round(avg, 3)
    return avg

# Create your views here.
class majorLV(LoginRequiredMixin, ListView):
    model = Course
    template_name = 'classes/majorAll.html'
    context_object_name = 'subjects'
    paginate_by = 20

    def get_queryset(self):
        return Course.objects.filter(year=datetime.today().year).order_by('grade', 'subjectName')


class majorDV(LoginRequiredMixin, TemplateView):
    template_name = 'classes/majorDetail.html'


    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(majorDV, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books

        # Subject_desription, Core_Competence, Learning_Objectives,
        # Lecture_method, Assignment, School_composition_ratio, Weekly_course_contents, Book
        try:
            context['subjectName'] = Course.objects.get(id=context['pk']).subjectName
        except:
            context['subjectName'] = None
        try:
            context['subjectDescriptions'] = Course.objects.get(id=context['pk']).desription
        except:
            context['subjectDescriptions'] = None
        try:
            temp = []
            temp.append(Course.objects.get(id=context['pk']).Knowledge_application)
            temp.append(Course.objects.get(id=context['pk']).verification_ability)
            temp.append(Course.objects.get(id=context['pk']).problem_solving)
            temp.append(Course.objects.get(id=context['pk']).tool_utilization)
            temp.append(Course.objects.get(id=context['pk']).design_ability)
            temp.append(Course.objects.get(id=context['pk']).teamwork_skill)
            temp.append(Course.objects.get(id=context['pk']).communication)
            temp.append(Course.objects.get(id=context['pk']).understanding_of_influence)
            temp.append(Course.objects.get(id=context['pk']).responsibility)
            temp.append(Course.objects.get(id=context['pk']).self_led)
            context['coreCompetences'] = temp
        except:
            context['coreCompetences'] = None
        try:
            temp = []
            temp.append(Course.objects.get(id=context['pk']).Lecture_type)
            temp.append(Course.objects.get(id=context['pk']).teaching_method)
            temp.append(Course.objects.get(id=context['pk']).educational_equipment)
            context['lectureMethods'] = temp
        except:
            context['lectureMethods'] = None
        try:
            temp = []
            temp.append(Course.objects.get(id=context['pk']).Assignment)
            context['assignments'] = temp
        except:
            context['assignments'] = None
        try:
            temp = []
            temp.append(Course.objects.get(id=context['pk']).Midterm_exam)
            temp.append(Course.objects.get(id=context['pk']).final_exam)
            temp.append(Course.objects.get(id=context['pk']).attendance)
            temp.append(Course.objects.get(id=context['pk']).assignments_and_others)
            temp.append(Course.objects.get(id=context['pk']).grading_division)
            context['schoolCompositionRatios'] = temp
        except:
            context['schoolCompositionRatios'] = None
        try:
            context['weeklyCourseContents'] = Weekly_course_contents.objects.filter(course_id=context['pk'])
        except:
            context['weeklyCourseContents'] = None
        try:
            temp = []
            temp.append(Course.objects.get(id=context['pk']).title)
            temp.append(Course.objects.get(id=context['pk']).author)
            temp.append(Course.objects.get(id=context['pk']).publisher)
            temp.append(Course.objects.get(id=context['pk']).year_of_publication)
            context['books'] = temp
        except:
            context['books'] = None

        subjectName = Course.objects.get(id=context['pk']).subjectName
        context['cnt'] = self.get_gradelist(subjectName)
        return context


    # 학번을 가진 학생의 이수한 학기 리스트를 가져옴
    def get_semesterlist(self, hukbun):
        semesterlist = []
        temp = StudentGrade.objects.filter(hukbun=hukbun).filter(valid='유효').values_list('yearNsemester', flat=True).order_by('yearNsemester').distinct()
        for i in range(0, temp.count()):
            semesterlist.append(temp[i])
        return semesterlist

    # 인덱스를 넣으면 학년을 리턴함
    def get_year(self, idx):
        if (idx == 7) or (idx == 6):
            return 4
        elif (idx == 5) or (idx == 4):
            return 3
        elif (idx == 3) or (idx == 2):
            return 2
        elif (idx == 1) or (idx == 0):
            return 1
        else:
            return 0

    def check_year(self, yearNsemester, semesterlist):
        idx = semesterlist.index(yearNsemester)

        return idx
    # 학번을 가진 학생의 이수한 학기 리스트를 가져옴
    # 과목 코스의 pk를 가지고 과목 이름을 리턴
    # 그 과목이름을 가진 그레이드 객체들을 리스트에 넣는다.
    # 그 성적 리스트에서 학번들만 가져와서 그 학번들이 몇학년인지 알아내어 딕셔너리에 {성적객체, 학년} 으로 추가 한다.
    # 딕셔너리를 학년별로 정렬한다.(오름차순)
    # 딕셔너리에 있는 학년별로 성적 객체의 수를 카운트한다.
    # 리스트 2개를 반환한다. [1학년, 2학년, ..,], [cnt1, cnt2, ...]
    def get_gradelist(self, subjectName):
        gradelist = []
        cnt = [0,0,0,0]
        dic = {}

        temp = StudentGrade.objects.filter(subject=subjectName)
        for i in range(0, temp.count()):
            gradelist.append(temp[i]) # 같은 과목이름을 가진 StudentGrade객체들을 리스트에 넣는다.

        print(gradelist)
        for i in range(0, len(gradelist)):
            semesterlist = self.get_semesterlist(gradelist[i].hukbun)
            idx = self.check_year(gradelist[i].yearNsemester, semesterlist)
            year = self.get_year(idx)
            dic[gradelist[i]] = year

        print("dic", end="")
        print(dic)
        dic = sorted(dic.items(), key=operator.itemgetter(1))
        print(dic)

        for object in dic:
            if object[1] == 1:
                cnt[0] = cnt[0] + 1
            elif object[1] == 2:
                cnt[1] = cnt[1] + 1
            elif object[1] == 3:
                cnt[2] = cnt[2] + 1
            elif object[1] == 4:
                cnt[3] = cnt[3] + 1
            else:
                continue

        print("cnt",end="")
        print(cnt)

        return cnt

class SpecialCourseRecommandView(LoginRequiredMixin, TemplateView):
    template_name = "classes/special_recommand.html"

    def get_context_data(self, **kwargs):
        context = super(SpecialCourseRecommandView, self).get_context_data(**kwargs)
        student = StudentInfo.objects.get(hukbun=self.request.user.hukbun)

        context['specialCoursesDic'] = self.getSpecialCase()
        return context

    def getSpecialCase(self):  # 자신의 학년과 맞지 않게 다른 학년의 수업을 들은 경우를 보여줌
        specialCoursesDic = dict()

        for student in StudentInfo.objects.all():  # 모든 학생
            studentGrades = StudentGrade.objects.filter(hukbun=student.hukbun)  # 학생의 grade 쿼리셋
            semesterList = studentGrades.values_list('yearNsemester', flat=True)  # 학생의 학기 list
            semesterList = sorted(list(set(semesterList)))  # 중복제거하여 정렬
            retakeList = [] #재수강한 과목들 -> 이 과목은 무시하자
            for grade in studentGrades:  # 학생이 과목을 들었을 때 학년이 일치하는 지 확인한다.
                if grade.valid == '재수강무효' or grade.valid == 'F학점일괄무효' or grade.subject in retakeList: #해당 과목이 재수강과목이라면 무시
                    retakeList.append(grade.subject)
                    continue
                semester = semesterList.index(grade.yearNsemester)  # 해당 과목의 학기가 semesterList에서 검색해 index를 반환한다 => 해당 과목이 몇학기에 들은 과목인가 검사
                courses = Course.objects.filter(year__in=[datetime.today().year-1, datetime.today().year], subjectName=grade.subject)  # 해당 수업의 이름과 동일한 course 쿼리셋 가져오기
                if courses.count() == 0:  # 만약 해당하는 수업이 없다면 걍 무시
                    continue
                courseInfoes = []
                course = courses.last() #수업을 대충 하나 가져와서 추천 학년을 저장
                courseGrade = course.grade  #해당 수업의 추천 학년 가져옴
                if int(semester / 2) + 1 != int(courseGrade):  # 추천 학년대로 과목을 안 들었을 경우
                    courseInfoes.append(course.grade)  # 추천 학년
                    courseInfoes.append(int(semester / 2) + 1)  # 들었던 학년
                    courseInfoes.append(course.eisu)  # 이수
                    courseInfoes.append(course.score)  # 학점
                    specialCoursesDic[grade] = courseInfoes

        # 이제 중복된 전공을 없애고 카운트하는게 필요
        grades = list(specialCoursesDic.keys())  # grade 객체 리스트
        gradesSubjectName = []
        resultDic = specialCoursesDic.copy()
        for grade in grades:  # grades := grades의 과목 이름 리스트
            gradesSubjectName.append(grade.subject)
        notDuplicatedGrades = list(set(gradesSubjectName))
        for notDuplicatedGrade in notDuplicatedGrades:

classes/templates/classes/majorAll.html
{% extends "base.html" %}
{% block title %}세부전공내역{% endblock %}

{% load staticfiles %}
{% block extrastyle %}



{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">세부 전공 내역</h1>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-11">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover table-striped">
                                <thead>
                                <tr>
                                    <th>년도</th>
                                    <th>학기</th>
                                    <th>과목명</th>
                                    <th>과목코드</th>
                                    <th>학년</th>
                                    <th>이수구분</th>
                                    <th>학점</th>
                                    <th>담당교수</th>
                                    <th>비교</th>
                                    <th>교시</th>
                                    <th>강의실</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for subject in subjects %}
                                    <td>{{ subject.year }}</td>
                                    {% if subject.semester == '10' %}
                                        <td>1</td>
                                    {% elif subject.semester == '20' %}
                                        <td>2</td>
                                    {% endif %}
                                    <td><a href="{% url 'classes:major_detail' subject.id %}">{{ subject.subjectName }}</a></td>
                                    <td>{{ subject.subjectCode }}</td>
                                    <td>{{ subject.grade }}</td>
                                    <td>{{ subject.eisu }}</td>
                                    <td>{{ subject.score }}</td>
                                    <td>{{ subject.professor }}</td>
                                    <td>{{ subject.remarks }}</td>
                                    <td>{{ subject.time }}</td>
                                    <td>{{ subject.lectureRoom }}</td>
                                    <tr />
                                {% endfor %}
                                </tbody>
                            </table>

                            <div>
                                <span>
                                    {% if page_obj.has_previous %}
                                        <a href="?page={{ page_obj.previous_page_number }}">PreviousPage</a>
                                    {% endif %}

                                    Page {{  page_obj.number }} of {{ page_obj.paginator.num_pages }}

                                    {% if page_obj.has_next %}
                                        <a href="?page={{ page_obj.next_page_number }}">NextPage</a>
                                    {% endif %}
                                </span>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

classes/templates/classes/majorDetail.html
{% extends "base.html" %}
{% block title %}전공상세정보{% endblock %}

{% load staticfiles %}
{% block extrastyle %}


{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{ subjectName }}</h1>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-10">
                        <ul>
                            <li><h4>교과목 해설</h4></li>
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <td>{{ subjectDescriptions }}</td>
                                    </tr>
                                </table>
                            </div>
                            <li><h4>세부핵심역량(학습성과)과의 관계</h4></li>
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <th>지식응용</th>
                                        <th>검증능력</th>
                                        <th>문제해결</th>
                                        <th>도구활용</th>
                                        <th>설계능력</th>
                                        <th>팀웍스킬</th>
                                        <th>의사전달</th>
                                        <th>영향이해</th>
                                        <th>책임의식</th>
                                        <th>자기주도</th>
                                    </tr>
                                    <tr>
                                        {% for coreCompetence in coreCompetences %}
                                            {% if coreCompetence == None %}
                                                <td></td>
                                            {% else %}
                                                <td>{{ coreCompetence}}</td>
                                            {% endif %}
                                        {% endfor %}
                                    </tr>
                                </table>
                            </div>
                            <li><h4>강의방법</h4></li>
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <th>강의형태</th>
                                        <td>{{ lectureMethods.0 }}</td>
                                        <th>수업방식</th>
                                        <td>{{ lectureMethods.1 }}</td>
                                        <th>교육용기자재</th>
                                        <td>{{ lectureMethods.2 }}</td>
                                    </tr>
                                </table>
                            </div>
                            <li><h4>과제물</h4></li>
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <th>과제물</th>
                                        <td>{{ assignments.0 }}</td>
                                    </tr>
                                </table>
                            </div>
                            <li><h4>성적구성비율</h4></li>
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <td>중간시험 {{ schoolCompositionRatios.0 }},    기말시험 {{ schoolCompositionRatios.1 }},    출석 {{ schoolCompositionRatios.2 }},    과제물 및 기타 {{ schoolCompositionRatios.3 }},    [성적평가구분 : {{ schoolCompositionRatios.4 }}]</td>
                                    </tr>
                                </table>
                            </div>
                            <li><h4>주별 강좌내용</h4></li>
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <th>주</th>
                                        <th>교수내용</th>
                                        <th>방법</th>
                                        <th>관련자료</th>
                                        <th>과제물</th>
                                    </tr>
                                    {% for weeklyCourseContent in weeklyCourseContents %}
                                        <tr>
                                            <td>{{ weeklyCourseContent.week }}</td>
                                            <td>{{ weeklyCourseContent.contents }}</td>
                                            <td>{{ weeklyCourseContent.methods }}</td>
                                            <td>{{ weeklyCourseContent.related_materials }}</td>
                                            <td>{{ weeklyCourseContent.assignments }}</td>
                                        </tr>
                                    {% endfor %}
                                </table>
                            </div>
                            <li><h4>교재</h4></li>
                            <div class="table-responsive">
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <th>도서명</th>
                                        <th>저자</th>
                                        <th>출판사</th>
                                        <th>출판년도</th>
                                    </tr>
                                    <tr>
                                        {% for book in books %}
                                            <td>{{ book }}</td>
                                        {% endfor %}
                                    </tr>
                                </table>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
            <div class="panel-body">
                <canvas id="Average" width="300" height="180"></canvas>
            </div>
            <script>
                var ctx = document.getElementById('Average').getContext('2d');
                var Average = new Chart(ctx, {
                    type: 'pie',
                    data: {
                        {#        labels: ['M', 'T', 'W', 'T', 'F', 'S', 'S'],#}
                        labels: ['1학년', '2학년', '3학년', '4학년'],
                        datasets: [
                            {
                                {#            data: [12, 19, 3, 17, 6, 3, 7],#}
                                data: [{% for c in cnt %} "{{ c }}", {% endfor %}],
                                backgroundColor: ['rgba(223, 240, 216,1)',
                                                    'rgba(242,222,222,1)',
                                                    'rgba(217, 237, 247,1)',
                                                'rgba(240,173,78,1)'
                                    ]
                            },
                        ]
                    },
                });
            </script>
        </div>
    </div>
{% endblock %}

classes/templates/classes/pre_recommand.html
{% extends "base.html" %}
{% block title %}수강신청추천{% endblock %}

{% load staticfiles %}
{% load custom %}
{% block extrastyle %}


{% endblock %}

{% block content %}
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">선수 과목에 따른 전공 추천</h1>
            </div>
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-10">
                        <ul>
                            <div class="table-responsive">
                                <li><h4>선수 과목 추천</h4></li>
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <th>과목명</th>
                                        <th>선수과목명</th>
                                        <th>선수과목 점수</th>
                                    </tr>
                                    {% for necessaryGrade in necessaryGrades %}
                                        <tr>
                                            <td>{{ necessaryGrade.0 }}</td>
                                            <td>{{ necessaryGrade.1.0 }}</td>
                                            <td>{{ necessaryGrade.2.0 }}</td>
                                        <tr />
                                    {% endfor %}
                                </table>
                            </div>
                            <div class="table-responsive">
                                <li><h4>권장 과목 추천</h4></li>
                                <table class="table table-bordered table-hover table-striped">
                                    <tr>
                                        <th>과목명</th>
                                        <th>권장과목명</th>
                                        <th>권장과목 점수</th>
                                    </tr>
                                    {% for promotedGrade in promotedGrades %}
                                        <tr>
                                            <td>{{ promotedGrade.0 }}</td>
                                            <td>{{ promotedGrade.1.0 }}</td>
                                            <td>{{ promotedGrade.2.0 }}</td>
                                        <tr />
                                    {% endfor %}
                                </table>
                            </div>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}